version: '3.2'

services:
  database:
    networks:
      - backend
    env_file:
      - prod-vars.env

  web:
    networks:
      - backend
      - frontend
    env_file:
      - prod-vars.env

  worker:
    networks:
      - backend
      - frontend
    env_file:
      - prod-vars.env

networks: 
  backend:
    internal: true
  frontend:
    internal: false
